apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-portfolio-rs
  namespace: kuma-system
  labels:
    app: my-portfolio
    type: frontend
spec:
  template:
    metadata:
      name: my-portfolio-rs
      namespace: kuma-system
      labels:
        app: my-portfolio
        type: frontend
    spec:
      containers:
      - name: my-portfolio
        image: portfolio:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: my-portfolio
      type: frontend

   
